# Week 1 — SQL Consolidation · 100 Drills
**Goal:** Lock in every concept from Days 1–5 before moving to Week 2.

**Databases:** `week1_ecommerce.db` (ecommerce) + `logistics_w2.db` (Canadian logistics)  
**Topics:** SELECT · WHERE · ORDER BY · GROUP BY · HAVING · Aggregates · JOINs · Subqueries

Questions build in difficulty within each section. No window functions.

---
## Setup — run this first

In [15]:
import sqlite3
import pandas as pd

eco = sqlite3.connect('week1_ecommerce.db')
log = sqlite3.connect(r'C:\Users\gianc\Documents\Logistics Operations Project\logistics_w2.db')
print('Connected to both databases')

Connected to both databases

---
## Table Preview — Ecommerce

In [16]:
for table in ['orders', 'customers', 'order_items']:
    print(f'\n--- {table} ---')
    df = pd.read_sql_query(f'SELECT * FROM {table} LIMIT 3', eco)
    print(f'Columns: {list(df.columns)}')
    display(df)

--- orders ---
Columns: ['order_id', 'customer_id', 'order_date', 'status', 'total_amount', 'region']

   order_id  customer_id  order_date     status  total_amount region
0      1001            1  2024-01-05  completed        250.00   West
1      1002            2  2024-01-12  cancelled         89.99   East
2      1003            3  2024-01-20  completed        430.50   West

--- customers ---
Columns: ['customer_id', 'name', 'email', 'signup_date', 'segment', 'country']

   customer_id          name            email signup_date  segment country
0            1  Alice Martin  alice@email.com  2022-03-15      VIP      US
1            2      Bob Chen    bob@email.com  2022-07-22  Regular      CA
2            3    Sara Lopez   sara@email.com  2023-01-10  Regular      US

--- order_items ---
Columns: ['item_id', 'order_id', 'product_name', 'category', 'quantity', 'unit_price']

   item_id  order_id    product_name     category  quantity  unit_price
0        1      1001  Wireless Mouse  Electronics         1        45.0
1        2      1001         USB Hub  Electronics         2        25.0
2        3      1001        Desk Mat  Accessories         1        35.0

---
## Table Preview — Logistics

In [17]:
for table in ['clients','warehouses','vehicles','drivers','routes','shipments','shipment_items']:
    print(f'\n--- {table} ---')
    df = pd.read_sql_query(f'SELECT * FROM {table} LIMIT 3', log)
    print(f'Columns: {list(df.columns)}')
    display(df)

--- clients ---
Columns: ['client_id', 'company', 'city', 'province', 'segment']

   client_id             company       city province     segment
0          1     Maple Retail Co    Toronto       ON  Enterprise
1          2   Pacific Goods Ltd  Vancouver       BC  Enterprise
2          3  Prairie Supply Inc    Calgary       AB         SMB

--- warehouses ---
Columns: ['warehouse_id', 'name', 'city', 'province', 'capacity_sqft']

   warehouse_id             name       city province  capacity_sqft
0             1  Toronto Central    Toronto       ON          85000
1             2    Vancouver Hub  Vancouver       BC          72000
2             3    Calgary Depot    Calgary       AB          55000

--- vehicles ---
Columns: ['vehicle_id', 'plate', 'type', 'max_kg']

   vehicle_id    plate   type  max_kg
0           1  ON-A001    Van   500.0
1           2  ON-A002    Van   500.0
2           3  BC-B001  Truck  3000.0

--- drivers ---
Columns: ['driver_id', 'name', 'province', 'hire_date', 'status']

   driver_id           name province   hire_date  status
0          1  Jean Tremblay       QC  2019-03-15  Active
1          2    Mike Okafor       ON  2020-07-01  Active
2          3     Sara Singh       BC  2018-11-20  Active

--- routes ---
Columns: ['route_id', 'origin_wh_id', 'dest_city', 'dest_province', 'distance_km']

   route_id  origin_wh_id dest_city dest_province  distance_km
0         1             1  Montreal            QC        541.0
1         2             1    Ottawa            ON        450.0
2         3             1   Halifax            NS       1800.0

--- shipments ---
Columns: ['shipment_id', 'client_id', 'route_id', 'driver_id', 'vehicle_id', 'ship_date', 'delivery_date', 'status', 'freight_charge']

,shipment_id,client_id,route_id,driver_id,vehicle_id,ship_date,delivery_date,status,freight_charge
0,1001,4,4,3,2,2024-11-23,2024-11-24,Delivered,3375.74
1,1002,2,10,7,1,2024-12-12,None,Delayed,4030.98
2,1003,10,1,9,4,2024-01-16,2024-01-20,Delivered,1162.07

--- shipment_items ---
Columns: ['item_id', 'shipment_id', 'description', 'category', 'weight_kg', 'declared_value']

   item_id  shipment_id      description  category  weight_kg  declared_value
0        1         1001      Electronics  Standard      787.6          321.17
1        2         1002  Office Supplies  Standard      614.3         3832.60
2        3         1002         Clothing  Standard       97.7         2512.06

---
# SECTION 1 — SELECT & WHERE (Q1–Q20)

**Q1 [eco]** — Show all columns from orders. Limit 10.

In [18]:
q1 = """ SELECT * FROM orders
LIMIT 10 

"""
df = pd.read_sql_query(q1, eco)
display(df)

   order_id  customer_id  order_date     status  total_amount region
0      1001            1  2024-01-05  completed        250.00   West
1      1002            2  2024-01-12  cancelled         89.99   East
2      1003            3  2024-01-20  completed        430.50   West
3      1004            4  2024-02-03   refunded        175.00  North
4      1005            1  2024-02-14  completed        310.00   East
5      1006            5  2024-03-01  cancelled         55.00   West
6      1007            2  2024-03-15  completed        620.00  South
7      1008            3  2024-04-02  completed        190.00   West
8      1009            6  2024-04-18   refunded        340.00   East
9      1010            4  2024-05-05  completed        510.00  North

**Q2 [eco]** — Show only order_id, status, and total_amount from orders.

In [19]:
q2 = """ SELECT order_id,
                status,
                total_amount
        FROM orders
        LIMIT 10
"""
df = pd.read_sql_query(q2, eco)
display(df)

   order_id     status  total_amount
0      1001  completed        250.00
1      1002  cancelled         89.99
2      1003  completed        430.50
3      1004   refunded        175.00
4      1005  completed        310.00
5      1006  cancelled         55.00
6      1007  completed        620.00
7      1008  completed        190.00
8      1009   refunded        340.00
9      1010  completed        510.00

**Q3 [eco]** — Show all completed orders.

In [20]:
q3 = """ SELECT order_id
        FROM orders
        WHERE status = 'completed'
        LIMIT 10


"""
df = pd.read_sql_query(q3, eco)
display(df)

   order_id
0      1001
1      1003
2      1005
3      1007
4      1008
5      1010
6      1012
7      1013
8      1015
9      1016

**Q4 [eco]** — Show all orders where total_amount is greater than $400.

In [21]:
q4 = """ SELECT order_id,   
                total_amount
        FROM orders
        WHERE total_amount > 400
        ORDER BY total_amount DESC

"""
df = pd.read_sql_query(q4, eco)
display(df)

    order_id  total_amount
0       1027         980.0
1       1018         890.0
2       1023         720.0
3       1030         640.0
4       1007         620.0
5       1021         560.0
6       1010         510.0
7       1013         480.0
8       1020         440.0
9       1003         430.5
10      1026         415.0

**Q5 [eco]** — Show all completed orders from the West region.

In [22]:
q5 = """ SELECT order_id
        FROM orders
        WHERE status = 'completed'
         AND region = 'West'
        
        

"""
df = pd.read_sql_query(q5, eco)
display(df)

   order_id
0      1001
1      1003
2      1008
3      1013
4      1023
5      1027
6      1030

**Q6 [eco]** — Show all orders that are cancelled or refunded. Use IN.

In [23]:
q6 = """ SELECT order_id,
                status
        FROM orders
        WHERE status IN ('cancelled','refunded')

"""
df = pd.read_sql_query(q6, eco)
display(df)

    order_id     status
0       1002  cancelled
1       1004   refunded
2       1006  cancelled
3       1009   refunded
4       1011  cancelled
5       1014   refunded
6       1017  cancelled
7       1020   refunded
8       1022  cancelled
9       1025   refunded
10      1028  cancelled

**Q7 [eco]** — Show all customers from the US. Show name, segment, country.

In [24]:
q7 = """ SELECT name,
                segment,
                country
        FROM customers 
        WHERE country = 'US'

"""
df = pd.read_sql_query(q7, eco)
display(df)

            name  segment country
0   Alice Martin      VIP      US
1     Sara Lopez  Regular      US
2     Priya Nair      New      US
3  Lily Thompson      New      US
4     Emma Rossi  Regular      US

**Q8 [eco]** — Show orders placed in Q4 2024 (October–December). Order by order_date ascending.

In [25]:
q8 = """ SELECT order_id
        FROM  orders
        WHERE order_date >= 01-10-2024 AND order_date <= 31-12-2024
        ORDER BY order_date DESC

"""
df = pd.read_sql_query(q8, eco)
display(df)

Empty DataFrame
Columns: [order_id]
Index: []

**Q9 [eco]** — Show all order_items in the Electronics category with unit_price above $100.

In [26]:
q9 = """ SELECT product_name,
                unit_price
        FROM order_items
        WHERE category = ' Electronics' AND unit_price > 100

"""
df = pd.read_sql_query(q9, eco)
display(df)

Empty DataFrame
Columns: [product_name, unit_price]
Index: []

**Q10 [eco]** — Show all VIP customers. Show name, email, country.

In [27]:
q10 = """ SELECT name,
                email,
                country
            FROM customers
            WHERE segment = 'VIP'

"""
df = pd.read_sql_query(q10, eco)
display(df)

            name             email country
0   Alice Martin   alice@email.com      US
1       James Wu   james@email.com      UK
2  Carlos Mendez  carlos@email.com      MX

**Q11 [log]** — Show all columns from drivers. Limit 10.

In [28]:
q11 = """ SELECT *
            FROM drivers
            LIMIT 10

"""
df = pd.read_sql_query(q11, log)
display(df)

   driver_id           name province   hire_date    status
0          1  Jean Tremblay       QC  2019-03-15    Active
1          2    Mike Okafor       ON  2020-07-01    Active
2          3     Sara Singh       BC  2018-11-20    Active
3          4   Tom Beaumont       AB  2021-02-10    Active
4          5    Priya Mehta       ON  2022-05-30    Active
5          6  Carlos Rivera       MB  2020-09-14    Active
6          7     Linda Park       BC  2019-01-08    Active
7          8  James Leblanc       NS  2023-03-01    Active
8          9   Aisha Diallo       QC  2021-11-15  Inactive
9         10  Ryan Kowalski       ON  2022-08-22    Active

**Q12 [log]** — Show all active drivers.

In [29]:
q12 = """ SELECT name
            FROM drivers
            WHERE status = 'Active'


"""
df = pd.read_sql_query(q12, log)
display(df)

            name
0  Jean Tremblay
1    Mike Okafor
2     Sara Singh
3   Tom Beaumont
4    Priya Mehta
5  Carlos Rivera
6     Linda Park
7  James Leblanc
8  Ryan Kowalski

**Q13 [log]** — Show all delivered shipments with freight_charge above $2000.

In [30]:
q13 = """ SELECT shipment_id
                FROM shipments
                WHERE status = 'Delivered' AND freight_charge > 2000


"""
df = pd.read_sql_query(q13, log)
display(df)

    shipment_id
0          1001
1          1008
2          1009
3          1010
4          1021
5          1024
6          1029
7          1035
8          1038
9          1048
10         1051
11         1056
12         1063
13         1064
14         1065
15         1068
16         1070
17         1075
18         1077
19         1080
20         1084
21         1087
22         1091
23         1094
24         1097
25         1098
26         1104
27         1107
28         1110
29         1117
30         1118
31         1120
32         1125
33         1127
34         1129
35         1132
36         1137
37         1140
38         1141
39         1142
40         1143
41         1144
42         1149
43         1152
44         1153
45         1162
46         1166
47         1168
48         1175
49         1181
50         1183
51         1184
52         1186
53         1188
54         1192

**Q14 [log]** — Show all shipments from Q4 2024 that were delayed.

In [31]:
q14 = """ SELECT shipment_id,
            ship_date
        FROM shipments 
        WHERE status = 'Delayed' AND ship_date >= '2024-09-01' AND ship_date <= '2024-12-31'
        ORDER BY ship_date DESC 

"""
df = pd.read_sql_query(q14, log)
display(df)

    shipment_id   ship_date
0          1002  2024-12-12
1          1033  2024-12-10
2          1164  2024-12-10
3          1045  2024-12-08
4          1086  2024-12-08
5          1039  2024-12-04
6          1004  2024-11-28
7          1105  2024-11-26
8          1193  2024-11-07
9          1095  2024-10-30
10         1083  2024-10-26
11         1040  2024-10-23
12         1071  2024-09-20
13         1138  2024-09-17

**Q15 [log]** — Show all Enterprise clients.

In [32]:
q15 = """ SELECT company
            FROM clients
            WHERE segment = 'Enterprise'

"""
df = pd.read_sql_query(q15, log)
display(df)

             company
0    Maple Retail Co
1  Pacific Goods Ltd
2    Rockies Imports

**Q16 [log]** — Show all routes with distance_km greater than 1000.

In [33]:
q16 = """ SELECT route_id
            FROM routes
            WHERE distance_km > 1000

"""
df = pd.read_sql_query(q16, log)
display(df)

   route_id
0         3
1         5
2         7

**Q17 [log]** — Show all shipment items in the Hazardous category.

In [34]:
q17 = """ SELECT Distinct(description)
            FROM shipment_items
            WHERE category = 'Hazardous'

"""
df = pd.read_sql_query(q17, log)
display(df)

            description
0             Batteries
1       Cleaning Agents
2                 Paint
3  Industrial Chemicals

**Q18 [log]** — Show all shipments that are cancelled or delayed. Use IN.

In [35]:
q18 = """ SELECT shipment_id,
                status
            FROM shipments
            WHERE status IN ('Cancelled', 'Delayed')

"""
df = pd.read_sql_query(q18, log)
display(df)

    shipment_id     status
0          1002    Delayed
1          1004    Delayed
2          1005  Cancelled
3          1006  Cancelled
4          1011    Delayed
..          ...        ...
68         1191  Cancelled
69         1193    Delayed
70         1194  Cancelled
71         1197  Cancelled
72         1198  Cancelled

[73 rows x 2 columns]

**Q19 [log]** — Show all warehouses in Ontario (province = 'ON').

In [36]:
q19 = """ SELECT warehouse_id,
                name
            FROM warehouses
            WHERE province = 'ON'

"""
df = pd.read_sql_query(q19, log)
display(df)

   warehouse_id             name
0             1  Toronto Central
1             7       Ottawa Gov

**Q20 [log]** — Show shipment items with declared_value above $3000 AND weight_kg below 100.

In [37]:
q20 = """ SELECT item_id,
                    description
            FROM shipment_items 
            WHERE declared_value > 3000 AND weight_kg < 100

"""
df = pd.read_sql_query(q20, log)
display(df)

    item_id           description
0         5        Dairy Products
1         6           Electronics
2        26           Electronics
3        27           Paper Goods
4        65               Seafood
5        76       Office Supplies
6       100              Ceramics
7       119            Auto Parts
8       129            Auto Parts
9       144            Auto Parts
10      170       Office Supplies
11      199              Hardware
12      217  Industrial Chemicals
13      242       Display Screens
14      256             Glassware
15      257        Dairy Products
16      366       Cleaning Agents
17      406         Lab Equipment
18      422              Clothing
19      441            Auto Parts
20      477           Paper Goods
21      492           Paper Goods
22      511         Fresh Produce
23      522       Cleaning Agents
24      524              Clothing
25      530         Fresh Produce
26      546          Frozen Foods
27      562           Electronics
28      594       Office Supplies
29      596              Hardware
30      598           Electronics
31      600             Glassware

---
# SECTION 2 — ORDER BY, Aggregates & GROUP BY (Q21–Q40)

**Q21 [eco]** — Show all completed orders sorted by total_amount descending.

In [38]:
q21 = """ SELECT order_id,
                total_amount
                FROM orders 
                WHERE status = 'completed'
                ORDER BY total_amount DESC


"""
df = pd.read_sql_query(q21, eco)
display(df)

    order_id  total_amount
0       1027         980.0
1       1018         890.0
2       1023         720.0
3       1030         640.0
4       1007         620.0
5       1021         560.0
6       1010         510.0
7       1013         480.0
8       1003         430.5
9       1026         415.0
10      1015         390.0
11      1024         335.0
12      1005         310.0
13      1029         290.0
14      1012         275.0
15      1001         250.0
16      1008         190.0
17      1019         165.0
18      1016         145.0

**Q22 [eco]** — Count total orders. Show as total_orders.

In [39]:
q22 = """ SELECT COUNT(order_id) AS total_orders
            FROM orders

            

"""
df = pd.read_sql_query(q22, eco)
display(df)

   total_orders
0            30

**Q23 [eco]** — Total revenue, average, max, and min — completed orders only.

In [40]:
q23 = """ SELECT SUM(total_amount) AS total_revenue,
                ROUND(AVG(total_amount),2) AS avg_order_revenue,
                MAX(total_amount) AS max_order_value,    
                MIN(total_amount) AS min_order_value
                FROM orders
                WHERE status = 'completed'


"""
df = pd.read_sql_query(q23, eco)
display(df)

   total_revenue  avg_order_revenue  max_order_value  min_order_value
0         8595.5             452.39            980.0            145.0

**Q24 [eco]** — Count orders by status. Show status and order_count. Highest count first.

In [41]:
q24 = """ SELECT status,
                COUNT(order_id) AS order_count
                FROM orders 
               GROUP BY status

"""
df = pd.read_sql_query(q24, eco)
display(df)

      status  order_count
0  cancelled            6
1  completed           19
2   refunded            5

**Q25 [eco]** — Total revenue by region — completed only. Highest first.

In [42]:
q25 = """ SELECT region,
                SUM(total_amount) AS total_revenue
            FROM orders
            WHERE status = 'completed'
            GROUP BY region
            ORDER BY total_revenue DESC
"""
df = pd.read_sql_query(q25, eco)
display(df)

  region  total_revenue
0   West         3690.5
1  South         2015.0
2   East         1590.0
3  North         1300.0

**Q26 [eco]** — Average order value per region — completed only. Round to 2dp.

In [43]:
q26 = """   SELECT region,
            ROUND(AVG(total_amount),2) AS avg_total_amount
            FROM orders
            WHERE status = 'completed'
            GROUP BY region
            ORDER BY avg_total_amount DESC

"""
df = pd.read_sql_query(q26, eco)
display(df)

  region  avg_total_amount
0   East            530.00
1   West            527.21
2  South            403.00
3  North            325.00

**Q27 [eco]** — Count orders per region AND status. Sort by region, then count descending.

In [44]:
q27 = """   SELECT region,
            status,
            COUNT(order_id) AS order_count
            FROM orders
            GROUP BY region, status

"""
df = pd.read_sql_query(q27, eco)
display(df)

  region     status  order_count
0   East  cancelled            3
1   East  completed            3
2   East   refunded            2
3  North  completed            4
4  North   refunded            2
5  South  completed            5
6   West  cancelled            3
7   West  completed            7
8   West   refunded            1

**Q28 [eco]** — Regions where total completed revenue exceeds $2000. Use HAVING.

In [45]:
q28 = """   SELECT region,
            SUM(total_amount) AS total_revenue
            FROM orders 
            WHERE status = 'completed'
            GROUP BY region
            HAVING total_revenue > 2000
            
            
"""
df = pd.read_sql_query(q28, eco)
display(df)

  region  total_revenue
0  South         2015.0
1   West         3690.5

**Q29 [eco]** — Regions where average completed order value is above $400. Use HAVING.

In [46]:
q29 = """   SELECT region,
            ROUND(AVG(total_amount),2) AS avg_total_amount
            FROM orders 
            WHERE status = 'completed' 
            GROUP BY region
            HAVING avg_total_amount > 400
            ORDER BY avg_total_amount DESC

"""
df = pd.read_sql_query(q29, eco)
display(df)

  region  avg_total_amount
0   East            530.00
1   West            527.21
2  South            403.00

**Q30 [log]** — Count shipments by status.

In [47]:
q30 = """  SELECT status,
            COUNT(shipment_id) AS shipment_count
            FROM shipments
            GROUP BY status
            ORDER BY shipment_count DESC
"""
df = pd.read_sql_query(q30, log)
display(df)

       status  shipment_count
0   Delivered             109
1   Cancelled              37
2     Delayed              36
3  In Transit              18

**Q31 [log]** — Total freight_charge by driver_id — delivered only. Highest first.

In [48]:
q31 = """   SELECT driver_id,
            SUM(freight_charge) AS total_freight_charge
            FROM shipments
            WHERE status = 'Delivered'
            GROUP BY driver_id  
            ORDER BY total_freight_charge DESC
"""
df = pd.read_sql_query(q31, log)
display(df)

   driver_id  total_freight_charge
0          3              37379.58
1          9              34477.68
2          7              33087.99
3          6              30453.34
4          8              27825.29
5          2              27143.77
6          4              22524.42
7          5              12719.59
8         10               9318.18
9          1               6682.19

**Q32 [log]** — Average freight_charge per route_id — delivered only. Round to 2dp.

In [49]:
q32 = """ SELECT r.route_id,
            ROUND(AVG(freight_charge),2) AS avg_freight_charge
        FROM routes r JOIN shipments s ON r.route_id = s.route_id
        WHERE status = 'Delivered'
        GROUP BY r.route_id
        ORDER BY avg_freight_charge DESC

"""
df = pd.read_sql_query(q32, log)
display(df)

    route_id  avg_freight_charge
0          5             2822.86
1          9             2792.48
2          7             2508.82
3          3             2395.27
4          2             2335.82
5         11             2335.35
6          8             2312.19
7         12             2078.13
8          6             2020.39
9          4             1909.21
10        10             1902.86
11         1             1377.47

**Q33 [log]** — Total declared_value of shipment items by category. Highest first.

In [50]:
q33 = """   SELECT category,
            ROUND(SUM(declared_value),2) AS total_declared_value
            FROM shipment_items
            GROUP BY category
            ORDER BY total_declared_value DESC


"""
df = pd.read_sql_query(q33, log)
display(df)

     category  total_declared_value
0    Standard             822987.41
1     Fragile             274654.64
2  Perishable             247542.81
3   Hazardous             211484.25

**Q34 [log]** — Total and average weight_kg of items per category. Round avg to 2dp.

In [51]:
q34 = """   SELECT category,
            SUM(weight_kg) AS total_weight,
            ROUND(AVG(weight_kg),2) AS avg_weight
        FROM shipment_items 
        GROUP BY category

"""
df = pd.read_sql_query(q34, log)
display(df)

     category  total_weight  avg_weight
0     Fragile       44908.1      408.26
1   Hazardous       30375.5      361.61
2  Perishable       40097.0      409.15
3    Standard      121812.7      395.50

**Q35 [log]** — driver_ids with more than 20 delivered shipments. Use HAVING.

In [52]:
q35 = """ SELECT driver_id,
            COUNT(shipment_id) AS delivered_shipments
        FROM shipments
        WHERE status = 'Delivered'
        GROUP BY driver_id
        HAVING delivered_shipments > 20

"""
df = pd.read_sql_query(q35, log)
display(df)

Empty DataFrame
Columns: [driver_id, delivered_shipments]
Index: []

**Q36 [log]** — Count shipments per client_id AND status. Sort by client_id, then count desc.

In [53]:
q36 = """   SELECT c.client_id,
            c.company,
            COUNT(s.shipment_id) AS total_shipments
            FROM clients c JOIN shipments s ON c.client_id = s.client_id
            GROUP BY c.client_id
            ORDER BY total_shipments DESC


"""
df = pd.read_sql_query(q36, log)
display(df)

   client_id             company  total_shipments
0         10      Lakeside Goods               24
1          8  Maritime Wholesale               23
2          4      Atlantic Foods               22
3          1     Maple Retail Co               22
4          6    Northern Freight               20
5          5    Capital Services               20
6          9     Crown Logistics               19
7          7     Rockies Imports               18
8          2   Pacific Goods Ltd               18
9          3  Prairie Supply Inc               14

**Q37 [log]** — Routes where average delivered freight exceeds $1500. Use HAVING.

In [54]:
q37 = """  SELECT route_id,
            ROUND(AVG(freight_charge),2) AS avg_freight_charge
        FROM shipments 
        WHERE status = 'Delivered'
        GROUP BY route_id
        HAVING avg_freight_charge > 1500
        ORDER BY avg_freight_charge DESC


"""
df = pd.read_sql_query(q37, log)
display(df)

    route_id  avg_freight_charge
0          5             2822.86
1          9             2792.48
2          7             2508.82
3          3             2395.27
4          2             2335.82
5         11             2335.35
6          8             2312.19
7         12             2078.13
8          6             2020.39
9          4             1909.21
10        10             1902.86

**Q38 [eco]** — Total item-level revenue SUM(quantity * unit_price) per category — all items in order_items.

In [55]:
q38 = """  SELECT oi.category,
            SUM(oi.quantity*oi.unit_price) AS item_revenue
            FROM order_items oi JOIN orders o ON oi.order_id = o.order_id
            WHERE status = 'completed' 
            GROUP BY category
            ORDER BY item_revenue DESC 

"""
df = pd.read_sql_query(q38, eco)
display(df)

      category  item_revenue
0  Electronics        3084.0
1    Furniture        1515.0
2  Accessories         517.5

**Q39 [log]** — Total freight AND total shipments per route_id AND status combination.

In [56]:
q39 = """ SELECT route_id,
                status,
                COUNT(shipment_id) AS shipment_count,
                SUM(freight_charge) AS total_freight_charge
        FROM shipments
        GROUP BY route_id, status

"""
df = pd.read_sql_query(q39, log)
display(df)

    route_id      status  shipment_count  total_freight_charge
0          1   Cancelled               3               6601.24
1          1     Delayed               4              12445.73
2          1   Delivered               8              11019.75
3          1  In Transit               2               4440.69
4          2   Cancelled               3               5724.79
5          2     Delayed               5              14262.93
6          2   Delivered              13              30365.64
7          2  In Transit               1               2296.79
8          3   Cancelled               1               2562.52
9          3     Delayed               1                798.10
10         3   Delivered               8              19162.14
11         3  In Transit               3               9950.31
12         4   Cancelled               1                318.45
13         4   Delivered              10              19092.13
14         4  In Transit               3               8211.86
15         5   Cancelled               4              10327.99
16         5     Delayed               5              14168.91
17         5   Delivered               9              25405.78
18         6   Cancelled               6              12529.58
19         6     Delayed               3               4323.83
20         6   Delivered              10              20203.91
21         6  In Transit               2               4294.41
22         7   Cancelled               6              13820.84
23         7     Delayed               5               9544.36
24         7   Delivered               8              20070.55
25         7  In Transit               2               5232.27
26         8   Cancelled               6              11959.13
27         8     Delayed               6              16587.30
28         8   Delivered               7              16185.31
29         9   Cancelled               3               4305.51
30         9     Delayed               1               2976.97
31         9   Delivered               7              19547.34
32         9  In Transit               1               3200.15
33        10   Cancelled               2               5966.80
34        10     Delayed               4               8342.67
35        10   Delivered              13              24737.20
36        11   Cancelled               1               2171.48
37        11     Delayed               1               3436.76
38        11   Delivered              10              23353.47
39        11  In Transit               2               7532.79
40        12   Cancelled               1               3044.23
41        12     Delayed               1               2798.59
42        12   Delivered               6              12468.81
43        12  In Transit               2               3012.14

**Q40 [log]** — Vehicle types with more than 30 delivered shipments. Use HAVING. Join shipments to vehicles.

In [57]:
q40 = """ SELECT v.type,
                COUNT(s.shipment_id) AS delivered_shipments
        FROM vehicles v JOIN shipments s ON v.vehicle_id = s.vehicle_id
        WHERE status = 'Delivered'
        GROUP BY v.type 
        HAVING delivered_shipments > 30

"""
df = pd.read_sql_query(q40, log)
display(df)

    type  delivered_shipments
0  Truck                   45
1    Van                   40

---
# SECTION 3 — JOINs (Q41–Q65)

**Q41 [eco]** — Each completed order with the customer's name and segment.

In [58]:
q41 = """   SELECT o.order_id,
                    c.name,
                    c.segment
            FROM orders o JOIN customers c ON o.customer_id = c.customer_id
            WHERE status = 'completed'
            GROUP BY o.order_id

"""
df = pd.read_sql_query(q41, eco)
display(df)

    order_id           name  segment
0       1001   Alice Martin      VIP
1       1003     Sara Lopez  Regular
2       1005   Alice Martin      VIP
3       1007       Bob Chen  Regular
4       1008     Sara Lopez  Regular
5       1010       James Wu      VIP
6       1012     Priya Nair      New
7       1013    Omar Hassan  Regular
8       1015   Alice Martin      VIP
9       1016      David Kim      New
10      1018  Carlos Mendez      VIP
11      1019       Bob Chen  Regular
12      1021       James Wu      VIP
13      1023    Omar Hassan  Regular
14      1024  Lily Thompson      New
15      1026     Emma Rossi  Regular
16      1027  Carlos Mendez      VIP
17      1029       Bob Chen  Regular
18      1030     Sara Lopez  Regular

**Q42 [eco]** — Each order item with the order's status and region. Limit 20.

In [59]:
q42 = """ SELECT o.order_id,
                oi.product_name,
                o.status,
                o.region
            FROM order_items oi JOIN orders o ON oi.order_id = o.order_id
            GROUP BY o.order_id, oi.product_name,o.region, o.status 

"""
df = pd.read_sql_query(q42, eco)
display(df)

    order_id          product_name     status region
0       1001              Desk Mat  completed   West
1       1001               USB Hub  completed   West
2       1001        Wireless Mouse  completed   West
3       1002           Phone Stand  cancelled   East
4       1003       Cable Organizer  completed   West
5       1003   Mechanical Keyboard  completed   West
6       1003         Monitor Light  completed   West
7       1004            Ring Light   refunded  North
8       1004                Webcam   refunded  North
9       1005         Standing Desk  completed   East
10      1006              Mousepad  cancelled   West
11      1007        Lumbar Cushion  completed  South
12      1007          Office Chair  completed  South
13      1008            HDMI Cable  completed   West
14      1008          Laptop Stand  completed   West
15      1009          Monitor 27in   refunded   East
16      1010       Ergonomic Mouse  completed  North
17      1010            Wrist Rest  completed  North
18      1011        Screen Cleaner  cancelled   West
19      1012            Headphones  completed  South
20      1013        Desk Organizer  completed   West
21      1013      Wireless Charger  completed   West
22      1014    Blue Light Glasses   refunded  North
23      1015            Keycap Set  completed   East
24      1015   Mechanical Keyboard  completed   East
25      1016            USB-C Dock  completed  South
26      1017          Gaming Chair  cancelled   West
27      1018           Monitor Arm  completed   East
28      1018     Ultrawide Monitor  completed   East
29      1019         Laptop Sleeve  completed  North
30      1020         Standing Desk   refunded   West
31      1021       Ergonomic Chair  completed  South
32      1022           Cable Clips  cancelled   East
33      1023             4K Webcam  completed   West
34      1023           Stream Deck  completed   West
35      1024  Noise Cancel Headset  completed  North
36      1025          Monitor 32in   refunded   East
37      1026             Desk Lamp  completed  South
38      1026     Wireless Keyboard  completed  South
39      1027        Curved Monitor  completed   West
40      1027         Monitor Stand  completed   West
41      1028          Mouse Pad XL  cancelled   East
42      1029    Laptop Cooling Pad  completed  North
43      1030          Monitor 27in  completed   West
44      1030         Standing Desk  completed   West

**Q43 [eco]** — Total revenue by customer segment — completed only. SUM(o.total_amount). Highest first.

In [60]:
q43 = """   SELECT c.segment,
            SUM(o.total_amount) AS segment_revenue
            FROM orders o JOIN customers c ON o.customer_id = c.customer_id
            WHERE status = 'completed'
            GROUP BY c.segment
            ORDER BY segment_revenue DESC


"""
df = pd.read_sql_query(q43, eco)
display(df)

   segment  segment_revenue
0  Regular           3950.5
1      VIP           3890.0
2      New            755.0

**Q44 [eco]** — Item-level revenue by category — completed only. SUM(oi.quantity * oi.unit_price). Highest first.

In [61]:
q44 = """ SELECT oi.category,
            SUM(oi.quantity*oi.unit_price) AS revenue
        FROM orders o JOIN order_items oi ON o.order_id = oi.order_id
        WHERE status = 'completed'
        GROUP BY oi.category
        ORDER BY revenue DESC
"""
df = pd.read_sql_query(q44, eco)
display(df)

      category  revenue
0  Electronics   3084.0
1    Furniture   1515.0
2  Accessories    517.5

**Q45 [eco]** — Top 5 customers by total spend — completed only. Show name, segment, total_spend.

In [62]:
q45 = """ SELECT c.name,
                c.segment,
                SUM(o.total_amount)  AS  total_spend

        FROM customers c JOIN orders o ON c.customer_id = o.customer_id
        WHERE status = 'completed'
        GROUP BY c.name, c.segment
        ORDER BY total_spend DESC

"""
df = pd.read_sql_query(q45, eco)
display(df)

            name  segment  total_spend
0  Carlos Mendez      VIP       1870.0
1     Sara Lopez  Regular       1260.5
2    Omar Hassan  Regular       1200.0
3       Bob Chen  Regular       1075.0
4       James Wu      VIP       1070.0
5   Alice Martin      VIP        950.0
6     Emma Rossi  Regular        415.0
7  Lily Thompson      New        335.0
8     Priya Nair      New        275.0
9      David Kim      New        145.0

**Q46 [eco]** — Revenue per region AND category — completed only. SUM(oi.quantity * oi.unit_price). Sort by region, revenue desc.

In [63]:
q46 = """   SELECT o.region,
            oi.category,
            SUM(oi.quantity*oi.unit_price) AS revenue
            FROM orders o JOIN order_items oi ON o.order_id = oi.order_id
            WHERE status = 'completed'
            GROUP BY o.region, oi.category
            ORDER BY o.region, revenue DESC   
"""
df = pd.read_sql_query(q46, eco)
display(df)

   region     category  revenue
0    East  Electronics    770.0
1    East    Furniture    310.0
2    East  Accessories    110.0
3   North  Electronics    360.0
4   North  Accessories     91.0
5   South    Furniture    895.0
6   South  Electronics    364.0
7   South  Accessories     65.0
8    West  Electronics   1590.0
9    West    Furniture    310.0
10   West  Accessories    251.5

**Q47 [eco]** — Average order value per segment — completed only. Round to 2dp. One row per segment.

In [64]:
q47 = """ SELECT c.segment,
                ROUND(AVG(o.total_amount),2) AS  avg_order_value
      FROM orders o JOIN customers c ON o.customer_id = c.customer_id
      WHERE status = 'completed' 
      GROUP BY c.segment 
      ORDER BY avg_order_value DESC
"""
df = pd.read_sql_query(q47, eco)
display(df)

   segment  avg_order_value
0      VIP           555.71
1  Regular           438.94
2      New           251.67

**Q48 [eco]** — Segments where total cancelled order value exceeds $100. Use HAVING.

In [65]:
q48 = """   SELECT c.segment,
                    SUM(o.total_amount) as cancelled_amount
            FROM customers c JOIN orders o ON c.customer_id = o.customer_id
            WHERE status = 'cancelled'
            GROUP BY c.segment
            HAVING cancelled_amount > 100
            ORDER BY cancelled_amount DESC


"""
df = pd.read_sql_query(q48, eco)
display(df)

   segment  cancelled_amount
0  Regular            399.99
1      New            228.00
2      VIP            125.00

**Q49 [eco]** — Customers who have never placed any order. LEFT JOIN + IS NULL.

In [66]:
q49 = """ SELECT c.name
        FROM customers c LEFT JOIN orders o ON c.customer_id  = o.customer_id
        WHERE o.order_id IS NULL
        
"""
df = pd.read_sql_query(q49, eco)
display(df)

Empty DataFrame
Columns: [name]
Index: []

**Q50 [eco]** — All customers and their order count — including zero-order customers. COUNT(o.order_id). Sort by order_count desc.

In [67]:
q50 = """   SELECT c.name,
                COUNT(o.order_id) AS total_orders
            FROM orders o LEFT JOIN customers c ON o.customer_id = c.customer_id
            GROUP BY c.name
            ORDER BY total_orders DESC 

"""
df = pd.read_sql_query(q50, eco)
display(df)

            name  total_orders
0     Sara Lopez             4
1       Bob Chen             4
2   Alice Martin             4
3     Priya Nair             3
4    Omar Hassan             3
5  Lily Thompson             3
6       James Wu             3
7     Emma Rossi             2
8      David Kim             2
9  Carlos Mendez             2

**Q51 [eco]** — Three-table join: revenue by segment AND category — completed only. SUM(oi.quantity * oi.unit_price). Sort by segment, revenue desc.

In [68]:
q51 = """ SELECT c.segment,
                oi.category,
                SUM(oi.quantity*oi.unit_price) AS revenue 
        FROM orders o JOIN order_items oi ON o.order_id = oi.order_id
        JOIN customers c ON o.customer_id = c.customer_id
        WHERE status = 'completed' 
        GROUP BY c.segment, oi.category
        ORDER BY c.segment, revenue DESC

"""
df = pd.read_sql_query(q51, eco)
display(df)

   segment     category  revenue
0      New  Electronics    489.0
1  Regular  Electronics   1055.0
2  Regular    Furniture    785.0
3  Regular  Accessories    271.5
4      VIP  Electronics   1540.0
5      VIP    Furniture    730.0
6      VIP  Accessories    246.0

**Q52 [log]** — Each delivered shipment with the driver's name. Limit 15.

In [69]:
q52 = """ SELECT d.name,
                COUNT(s.shipment_id) AS  delivered_shipments
        FROM shipments s JOIN drivers d ON s.driver_id = d.driver_id
        WHERE s.status = 'Delivered'
        GROUP BY d.name
        ORDER BY delivered_shipments DESC
        LIMIT 15

"""
df = pd.read_sql_query(q52, log)
display(df)

            name  delivered_shipments
0     Sara Singh                   15
1   Aisha Diallo                   15
2    Mike Okafor                   13
3  James Leblanc                   13
4     Linda Park                   12
5  Carlos Rivera                   12
6   Tom Beaumont                    9
7    Priya Mehta                    9
8  Ryan Kowalski                    8
9  Jean Tremblay                    3

**Q53 [log]** — Each shipment with client's company name and segment. Limit 15.

In [70]:
q53 = """   SELECT c.company,
                    c.segment,
                    s.shipment_id

            FROM shipments s JOIN clients c ON s.client_id = c.client_id
            GROUP BY c.company, c.segment, s.shipment_id
            LIMIT 15

"""
df = pd.read_sql_query(q53, log)
display(df)

              company     segment  shipment_id
0      Atlantic Foods         SMB         1001
1   Pacific Goods Ltd  Enterprise         1002
2      Lakeside Goods         SMB         1003
3      Atlantic Foods         SMB         1004
4     Rockies Imports  Enterprise         1005
5   Pacific Goods Ltd  Enterprise         1006
6     Maple Retail Co  Enterprise         1007
7      Lakeside Goods         SMB         1008
8    Capital Services  Government         1009
9    Northern Freight         SMB         1010
10  Pacific Goods Ltd  Enterprise         1011
11    Crown Logistics  Government         1012
12   Northern Freight         SMB         1013
13   Northern Freight         SMB         1014
14     Atlantic Foods         SMB         1015

**Q54 [log]** — Total freight by driver name — delivered only. Highest first.

In [71]:
q54 = """   SELECT d.name,
                    SUM(s.freight_charge) AS total_freight_charge
            FROM shipments s JOIN drivers d ON s.driver_id = d.driver_id
            WHERE s.status = 'Delivered'
            GROUP BY d.name
            ORDER BY total_freight_charge DESC
"""
df = pd.read_sql_query(q54, log)
display(df)

            name  total_freight_charge
0     Sara Singh              37379.58
1   Aisha Diallo              34477.68
2     Linda Park              33087.99
3  Carlos Rivera              30453.34
4  James Leblanc              27825.29
5    Mike Okafor              27143.77
6   Tom Beaumont              22524.42
7    Priya Mehta              12719.59
8  Ryan Kowalski               9318.18
9  Jean Tremblay               6682.19

**Q55 [log]** — Total freight by client segment — delivered only.

In [72]:
q55 = """   SELECT c.company,
                    c.segment,
                    SUM(s.freight_charge) AS total_freight_charge
            FROM shipments s JOIN clients c ON s.client_id = c.client_id 
            WHERE s.status = 'Delivered'
            GROUP BY c.company, c.segment
            ORDER BY  total_freight_charge DESC 
"""
df = pd.read_sql_query(q55, log)
display(df)

              company     segment  total_freight_charge
0     Crown Logistics  Government              31224.32
1      Lakeside Goods         SMB              28937.83
2    Northern Freight         SMB              28319.16
3  Maritime Wholesale         SMB              28314.27
4    Capital Services  Government              24117.47
5     Rockies Imports  Enterprise              23644.64
6      Atlantic Foods         SMB              20618.91
7     Maple Retail Co  Enterprise              19827.09
8  Prairie Supply Inc         SMB              19396.22
9   Pacific Goods Ltd  Enterprise              17212.12

**Q56 [log]** — Each shipment item with the shipment's status and ship_date. Limit 15.

In [73]:
q56 = """  SELECT   si.shipment_id,
                   si.description,
                    s.status,
                    s.ship_date
            FROM shipments s JOIN shipment_items si ON s.shipment_id = si.shipment_id
            GROUP BY  si.shipment_id, si.description, s.status, s.ship_date
            LIMIT 15

"""
df = pd.read_sql_query(q56, log)
display(df)

    shipment_id      description     status   ship_date
0          1001      Electronics  Delivered  2024-11-23
1          1002         Clothing    Delayed  2024-12-12
2          1002  Office Supplies    Delayed  2024-12-12
3          1003   Dairy Products  Delivered  2024-01-16
4          1003      Electronics  Delivered  2024-01-16
5          1003         Hardware  Delivered  2024-01-16
6          1003  Office Supplies  Delivered  2024-01-16
7          1004       Auto Parts    Delayed  2024-11-28
8          1004  Display Screens    Delayed  2024-11-28
9          1004         Hardware    Delayed  2024-11-28
10         1005        Batteries  Cancelled  2024-01-04
11         1005         Clothing  Cancelled  2024-01-04
12         1005         Hardware  Cancelled  2024-01-04
13         1006       Auto Parts  Cancelled  2024-04-20
14         1006    Fresh Produce  Cancelled  2024-04-20

**Q57 [log]** — Total declared_value of items per shipment status. Join shipment_items to shipments.

In [74]:
q57 = """    SELECT s.status,
                    SUM(si.declared_value) AS total_declared_value
            FROM shipments s JOIN shipment_items si ON s.shipment_id = si.shipment_id
            GROUP BY s.status
            ORDER BY total_declared_value DESC
"""
df = pd.read_sql_query(q57, log)
display(df)

       status  total_declared_value
0   Delivered             831415.64
1   Cancelled             299538.01
2     Delayed             271496.73
3  In Transit             154218.73

**Q58 [log]** — Clients with no shipments at all. LEFT JOIN + IS NULL.

In [75]:
q58 = """    SELECT c.company
            FROM shipments s LEFT JOIN clients c ON s.client_id = c.client_id
            WHERE shipment_id IS NULL
            
"""
df = pd.read_sql_query(q58, log)
display(df)

Empty DataFrame
Columns: [company]
Index: []

**Q59 [log]** — Route destination city and total delivered freight per route. Highest first. Join shipments to routes.

In [76]:
q59 = """  SELECT   r.route_id,
                    r.dest_city,
                    SUM(s.freight_charge)  AS  total_freight_charge
            FROM shipments s JOIN routes r ON s.route_id = r.route_id
            WHERE s.status = 'Delivered' 
            GROUP BY r.route_id, r.dest_city
"""
df = pd.read_sql_query(q59, log)
display(df)

    route_id    dest_city  total_freight_charge
0          1     Montreal              11019.75
1          2       Ottawa              30365.64
2          3      Halifax              19162.14
3          4      Calgary              19092.13
4          5     Winnipeg              25405.78
5          6     Edmonton              20203.91
6          7     Winnipeg              20070.55
7          8  Quebec City              16185.31
8          9       Ottawa              19547.34
9         10      Moncton              24737.20
10        11  Thunder Bay              23353.47
11        12      Toronto              12468.81

**Q60 [log]** — Three-table join: total freight per client segment AND driver province — delivered only.

In [77]:
q60 = """       SELECT c.segment,
                        d.province,
                        SUM(s.freight_charge) AS total_freight_charge 
                FROM shipments s JOIN clients c ON s.client_id = c.client_id
                JOIN drivers d ON s.driver_id = d.driver_id
                WHERE s.status = 'Delivered'
                GROUP BY c.segment, d.province
                

"""
df = pd.read_sql_query(q60, log)
display(df)

       segment province  total_freight_charge
0   Enterprise       AB               4145.64
1   Enterprise       BC              20516.01
2   Enterprise       MB               4311.54
3   Enterprise       NS               5532.90
4   Enterprise       ON              10827.42
5   Enterprise       QC              15350.34
6   Government       AB               3026.50
7   Government       BC              11200.55
8   Government       MB              13671.13
9   Government       NS               5407.09
10  Government       ON              11796.81
11  Government       QC              10239.71
12         SMB       AB              15352.28
13         SMB       BC              38751.01
14         SMB       MB              12470.67
15         SMB       NS              16885.30
16         SMB       ON              26557.31
17         SMB       QC              15569.82

**Q61 [log]** — Drivers with more than 15 delivered shipments — show driver name and count. Use HAVING.

In [78]:
q61 = """  SELECT d.name,
                    COUNT(s.shipment_id) AS delivered_shipments 
            FROM shipments s JOIN drivers d ON s.driver_id = d.driver_id
            WHERE s.status = 'Delivered'
            GROUP BY d.name 
            HAVING delivered_shipments > 15

"""
df = pd.read_sql_query(q61, log)
display(df)

Empty DataFrame
Columns: [name, delivered_shipments]
Index: []

**Q62 [log]** — All drivers and how many delivered shipments each has — including 0. COUNT(s.shipment_id).

In [79]:
q62 = """   SELECT d.name,
                    COUNT(s.shipment_id) AS delivered_shipments

            FROM shipments s LEFT JOIN drivers d ON s.driver_id = d.driver_id
                WHERE s.status = 'Delivered' 
            GROUP BY d.name
"""
df = pd.read_sql_query(q62, log)
display(df)

            name  delivered_shipments
0   Aisha Diallo                   15
1  Carlos Rivera                   12
2  James Leblanc                   13
3  Jean Tremblay                    3
4     Linda Park                   12
5    Mike Okafor                   13
6    Priya Mehta                    9
7  Ryan Kowalski                    8
8     Sara Singh                   15
9   Tom Beaumont                    9

**Q63 [eco]** — Cancelled orders over $100 with customer name and segment. Highest amount first.

In [80]:
q63 = """ SELECT c.name,
                    c.segment,
                    o.total_amount
          FROM orders o JOIN customers c ON o.customer_id = c.customer_id
          WHERE status = 'cancelled' AND total_amount > 100
          GROUP BY c.name, c.segment, o.total_amount
          ORDER BY o.total_amount DESC 


"""
df = pd.read_sql_query(q63, eco)
display(df)

           name  segment  total_amount
0    Emma Rossi  Regular         310.0
1  Alice Martin      VIP         125.0

**Q64 [log]** — Each shipment with driver name, client company, and route destination city. Delivered only. Limit 15.

In [81]:
q64 = """ SELECT s.shipment_id,
                d.name,
                c.company,
                r.dest_city
          FROM shipments s JOIN clients c ON s.client_id = c.client_id
          JOIN drivers d ON s.driver_id = d.driver_id
          JOIN routes r ON s.route_id = r.route_id
        WHERE s.status = 'Delivered'
        GROUP BY s.shipment_id, d.name, c.company, r.dest_city
        LIMIT 15


"""
df = pd.read_sql_query(q64, log)
display(df)

    shipment_id           name             company dest_city
0          1001     Sara Singh      Atlantic Foods   Calgary
1          1003   Aisha Diallo      Lakeside Goods  Montreal
2          1008  Ryan Kowalski      Lakeside Goods  Edmonton
3          1009   Tom Beaumont    Capital Services    Ottawa
4          1010  Carlos Rivera    Northern Freight   Halifax
5          1012  Carlos Rivera     Crown Logistics   Calgary
6          1015   Aisha Diallo      Atlantic Foods   Toronto
7          1018  James Leblanc     Rockies Imports   Moncton
8          1021    Mike Okafor  Prairie Supply Inc    Ottawa
9          1023  Carlos Rivera     Maple Retail Co    Ottawa
10         1024  James Leblanc   Pacific Goods Ltd    Ottawa
11         1028   Tom Beaumont      Lakeside Goods    Ottawa
12         1029    Mike Okafor     Maple Retail Co   Calgary
13         1030   Aisha Diallo  Maritime Wholesale   Calgary
14         1034     Linda Park  Maritime Wholesale   Halifax

**Q65 [eco]** — Item-level revenue per product name — completed only. SUM(oi.quantity * oi.unit_price). Top 10.

In [82]:
q65 = """   SELECT oi.product_name,
                    SUM(oi.quantity*oi.unit_price) AS revenue
            FROM orderS o JOIN order_items oi ON o.order_id = oi.order_id
            WHERE status = 'completed'
            GROUp BY oi.product_name
            ORDER BY revenue DESC 
            LIMIT 10


"""
df = pd.read_sql_query(q65, eco)
display(df)

           product_name  revenue
0     Ultrawide Monitor    650.0
1         Standing Desk    620.0
2        Curved Monitor    580.0
3          Office Chair    420.0
4       Ergonomic Chair    420.0
5          Monitor 27in    340.0
6   Mechanical Keyboard    240.0
7  Noise Cancel Headset    220.0
8            Headphones    180.0
9             4K Webcam    180.0

---
# SECTION 4 — Subqueries (Q66–Q100)

**Q66 [eco]** — Completed orders above the average completed order value. Subquery in WHERE.

In [83]:
q66 = """   SELECT COUNT(order_id) AS completed_orders
            FROM orders 
            WHERE status = 'completed' AND total_amount > ( SELECT AVG(total_amount) AS avg_amount
                                                    FROM orders
                                                      WHERE status = 'completed'
                                              )
        

"""
df = pd.read_sql_query(q66, eco)
display(df)

   completed_orders
0                 8

**Q67 [eco]** — Customers whose total completed spend is above the average customer spend. Show name, segment, total_spend.

In [84]:
q67 = """   SELECT c.name,
                    c.segment,  
                    SUM(o.total_amount) AS total_spend
            FROM orders o JOIN customers c ON o.customer_id = c.customer_id
            WHERE status = 'completed' AND total_amount > (SELECT AVG(total_amount) AS avg_spend
                                                             FROM orders)
            GROUP BY c.name, c.segment
            

"""
df = pd.read_sql_query(q67, eco)
display(df)

            name  segment  total_spend
0   Alice Martin      VIP        390.0
1       Bob Chen  Regular        620.0
2  Carlos Mendez      VIP       1870.0
3     Emma Rossi  Regular        415.0
4       James Wu      VIP       1070.0
5    Omar Hassan  Regular       1200.0
6     Sara Lopez  Regular       1070.5

**Q68 [eco]** — Subquery in FROM: average order value per segment at item grain. Inner: SUM(oi.quantity * oi.unit_price) per order_id + segment. Outer: AVG per segment.

In [85]:
q68 = """  SELECT   segment,
                    AVG (order_value) AS avg_order_value
                    FROM  (SELECT  c.segment,
                                    o.order_id,
                                SUM(oi.quantity*oi.unit_price) AS order_value
                                FROM  orders o JOIN order_items oi ON o.order_id = oi.order_id
                                    JOIN customers c ON o.customer_id = c.customer_id
                                    GROUP BY c.segment, o.order_id
                    ) sub
            GROUP BY segment
            
"""
df = pd.read_sql_query(q68, eco)
display(df)

   segment  avg_order_value
0      New       136.000000
1  Regular       238.037692
2      VIP       299.777778

**Q69 [eco]** — Proof drill: AVG(o.total_amount) vs item grain subquery. Run both and observe if they differ.

In [86]:
# Version A — order-level AVG
q69a = """ SELECT AVG(total_amount)
            FROM orders
            

"""
df = pd.read_sql_query(q69a, eco)
display(df)

   AVG(total_amount)
0            357.283

In [87]:
# Version B — item grain subquery AVG
q69b = """ SELECT AVG(item_rev) AS avg_total_amount
            FROM (  SELECT order_id,
                    SUM(quantity*unit_price) AS item_rev
                    FROM order_items
                    GROUP BY order_id
                ) 

"""
df = pd.read_sql_query(q69b, eco)
display(df)

   avg_total_amount
0        229.349667

**Q70 [eco]** — Regions where total completed revenue is above the average regional revenue.

In [88]:
q70 = """ SELECT region,
                total_amount
       FROM orders
       WHERE status = 'completed' AND total_amount > ( SELECT AVG(total_amount)
                                                        FROM orders
                                                        WHERE status = 'completed')
        GROUP BY region
"""
df = pd.read_sql_query(q70, eco)
display(df)

  region  total_amount
0   East         890.0
1  North         510.0
2  South         620.0
3   West         480.0

**Q71 [eco]** — Customers who placed orders in the West region. Subquery with IN.

In [89]:
q71 = """ SELECT c.name
        FROM orders o JOIN customers c ON o.customer_id = c.customer_id
        WHERE region IN ('West')
        GROUP BY c.name
"""
df = pd.read_sql_query(q71, eco)
display(df)

            name
0   Alice Martin
1  Carlos Mendez
2     Emma Rossi
3  Lily Thompson
4    Omar Hassan
5     Priya Nair
6     Sara Lopez

**Q72 [eco]** — Customers with NEVER a completed order. Correct LEFT JOIN pattern: subquery inside JOIN filtered to completed, then IS NULL.

In [90]:
q72 = """ SELECT c.name
      FROM orders o LEFT JOIN customers c ON o.customer_id = c.customer_id
        WHERE status = 'completed' AND order_id IS NULL
        GROUP BY c.name
"""
df = pd.read_sql_query(q72, eco)
display(df)

Empty DataFrame
Columns: [name]
Index: []

**Q73 [eco]** — Proof drill: wrong vs correct LEFT JOIN for zero-completed-order customers. Run both, compare row counts and what they actually return.

In [91]:
# Wrong: WHERE status <> 'completed'
q73a = """ SELECT c.name
         FROM orders o LEFT JOIN customers c ON o.customer_id = c.customer_id
         WHERE status <> 'completed'
        GROUP BY c.name

"""
df = pd.read_sql_query(q73a, eco)
display(df)

            name
0   Alice Martin
1       Bob Chen
2      David Kim
3     Emma Rossi
4       James Wu
5  Lily Thompson
6    Omar Hassan
7     Priya Nair
8     Sara Lopez

In [92]:
# Correct: subquery pre-filter + IS NULL
q73b = """ SELECT c.name
            FROM orders o LEFT JOIN customers c ON o.customer_id = c.customer_id
            WHERE status IN ('cancelled', 'refunded') IS NULL
        GROUP BY c.name

"""
df = pd.read_sql_query(q73b, eco)
display(df)

Empty DataFrame
Columns: [name]
Index: []

**Q74 [eco]** — For each customer, their single highest completed order. Correlated subquery.

In [93]:
q74 = """   
           SELECT c.name,
       o.total_amount
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
WHERE o.status = 'completed'
AND o.total_amount = (
    SELECT MAX(o2.total_amount)
    FROM orders o2
    WHERE o2.customer_id = o.customer_id
    AND o2.status = 'completed'
)
ORDER BY c.name

"""
df = pd.read_sql_query(q74, eco)
display(df)

            name  total_amount
0   Alice Martin         390.0
1       Bob Chen         620.0
2  Carlos Mendez         980.0
3      David Kim         145.0
4     Emma Rossi         415.0
5       James Wu         560.0
6  Lily Thompson         335.0
7    Omar Hassan         720.0
8     Priya Nair         275.0
9     Sara Lopez         640.0

**Q75 [eco]** — For each region, the top product category by item-level revenue. Correlated subquery in SELECT.

In [94]:
q75 = """  SELECT o.region,
       oi.category,
       
       (SELECT SUM(oi2.quantity * oi2.unit_price)
        FROM order_items oi2
        JOIN orders o2 ON oi2.order_id = o2.order_id
        WHERE o2.region = o.region) AS region_total
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY o.region, oi.category
ORDER BY o.region


"""
df = pd.read_sql_query(q75, eco)
display(df)

   region     category  region_total
0    East  Accessories       2092.99
1    East  Electronics       2092.99
2    East    Furniture       2092.99
3   North  Accessories        650.00
4   North  Electronics        650.00
5   South  Accessories       1324.00
6   South  Electronics       1324.00
7   South    Furniture       1324.00
8    West  Accessories       2813.50
9    West  Electronics       2813.50
10   West    Furniture       2813.50

**Q76 [log]** — Delivered shipments above the average delivered freight charge.

In [95]:
q76 = """ SELECT shipment_id,
                freight_charge AS above_average_freight
        FROM shipments 
        WHERE status = 'Delivered' AND above_average_freight > (SELECT AVG(freight_charge)
                                                                 FROM shipments
                                                                WHERE status = 'Delivered')
        GROUP BY shipment_id
        ORDER BY above_average_freight DESC

"""
df = pd.read_sql_query(q76, log)
display(df)

    shipment_id  above_average_freight
0          1107                4485.35
1          1183                4476.63
2          1175                4445.74
3          1141                4416.37
4          1021                4377.71
5          1143                4349.29
6          1188                4311.32
7          1065                4277.60
8          1153                4261.78
9          1038                4180.35
10         1166                4105.84
11         1080                4034.67
12         1024                3969.34
13         1035                3954.01
14         1129                3881.14
15         1084                3862.50
16         1192                3826.42
17         1091                3800.65
18         1048                3776.79
19         1110                3771.93
20         1075                3647.88
21         1149                3613.22
22         1184                3599.97
23         1056                3543.51
24         1162                3430.56
25         1142                3389.47
26         1001                3375.74
27         1144                3292.63
28         1104                3282.32
29         1181                3248.95
30         1064                3233.22
31         1029                3229.11
32         1120                3208.00
33         1186                3043.22
34         1009                3026.50
35         1118                3022.86
36         1010                2915.23
37         1098                2914.80
38         1117                2851.47
39         1077                2815.04
40         1125                2751.46
41         1087                2724.73
42         1094                2654.72
43         1008                2551.38
44         1068                2533.53
45         1132                2405.21
46         1097                2350.93
47         1051                2348.53
48         1140                2256.89

**Q77 [log]** — Drivers whose total delivered freight is above the average driver total freight. Show name and total.

In [96]:
q77 = """  SELECT d.driver_id,
                d.name,   
                freight_charge as above_avg_delivered_freight
            FROM shipments s JOIN drivers d ON s.driver_id = d.driver_id
            WHERE s.status = 'Delivered' AND above_avg_delivered_freight > (SELECT AVG(freight_charge)
                                                                            FROM shipments
                                                                            WHERE status = 'Delivered'
                                                                            )
            GROUP BY d.driver_id
            ORDER BY above_avg_delivered_freight DESC
"""
df = pd.read_sql_query(q77, log)
display(df)

   driver_id           name  above_avg_delivered_freight
0          2    Mike Okafor                      4377.71
1          7     Linda Park                      4180.35
2          8  James Leblanc                      3969.34
3          9   Aisha Diallo                      3954.01
4          1  Jean Tremblay                      3647.88
5          3     Sara Singh                      3375.74
6          4   Tom Beaumont                      3026.50
7          6  Carlos Rivera                      2915.23
8         10  Ryan Kowalski                      2551.38
9          5    Priya Mehta                      2533.53

**Q78 [log]** — Routes where total delivered freight exceeds the average route freight.

In [97]:
q78 = """  SELECT r.route_id,
                    r.dest_city,
                    freight_charge AS above_avg_route_freight

  FROM shipments s JOIN routes r ON s.route_id = r.route_id
  WHERE status = 'Delivered' AND above_avg_route_freight > ( SELECT AVG(freight_charge)
                                                            FROM shipments
                                                            WHERE status = 'Delivered'
                                                             )
    GROUP BY r.route_id, r.dest_city
    ORDER BY above_avg_route_freight DESC
"""
df = pd.read_sql_query(q78, log)
display(df)

    route_id    dest_city  above_avg_route_freight
0          9       Ottawa                  4377.71
1          5     Winnipeg                  4180.35
2          8  Quebec City                  3954.01
3         10      Moncton                  3776.79
4          4      Calgary                  3375.74
5         11  Thunder Bay                  3292.63
6          2       Ottawa                  3026.50
7          3      Halifax                  2915.23
8         12      Toronto                  2914.80
9          7     Winnipeg                  2815.04
10         6     Edmonton                  2551.38
11         1     Montreal                  2348.53

**Q79 [log]** — Subquery in FROM: average freight per delivery per driver. Inner: per shipment. Outer: avg per driver.

In [98]:
q79 = """ SELECT d.driver_id,
                d.name,
            ROUND(AVG(total_freight),2) AS avg_freight
          FROM drivers d JOIN ( SELECT shipment_id,
                                        driver_id,
                                SUM(freight_charge) AS total_freight
                                FROM shipments
                                GROUP BY shipment_id
                                ) AS per_shipment ON d.driver_id = per_shipment.driver_id
         GROUP BY d.driver_id, d.name
         ORDER BY avg_freight DESC
"""
df = pd.read_sql_query(q79, log)
display(df)

   driver_id           name  avg_freight
0          1  Jean Tremblay      2833.31
1          7     Linda Park      2756.66
2          6  Carlos Rivera      2559.87
3          3     Sara Singh      2514.61
4          4   Tom Beaumont      2301.82
5          2    Mike Okafor      2153.24
6          9   Aisha Diallo      2141.28
7          8  James Leblanc      2115.10
8          5    Priya Mehta      1920.67
9         10  Ryan Kowalski      1609.48

**Q80 [log]** — Clients with only cancelled or delayed shipments — use NOT IN to exclude any client with a delivered shipment.

In [99]:
q80 = """SELECT c.client_id,
                c.company
        FROM shipments s JOIN clients c ON s.client_id = c.client_id
        WHERE c.client_id NOT IN (SELECT client_id 
                                  FROM shipments
                                   WHERE status = 'Delivered'
                                   AND client_id IS NOT NULL)
        

"""
df = pd.read_sql_query(q80, log)
display(df)

Empty DataFrame
Columns: [client_id, company]
Index: []

**Q81 [log]** — For each driver, their single highest freight shipment. Correlated subquery.

In [100]:
q81 = """ SELECT d.driver_id,
       d.name,
       (SELECT MAX(s.freight_charge)
        FROM shipments s
        WHERE s.driver_id = d.driver_id) AS highest_freight
FROM drivers d
ORDER BY highest_freight DESC
        
"""
df = pd.read_sql_query(q81, log)
display(df)

   driver_id           name  highest_freight
0          4   Tom Beaumont          4496.88
1          6  Carlos Rivera          4485.35
2          8  James Leblanc          4476.63
3          3     Sara Singh          4445.74
4          7     Linda Park          4431.12
5          9   Aisha Diallo          4429.72
6          2    Mike Okafor          4377.71
7          1  Jean Tremblay          4245.12
8          5    Priya Mehta          3976.43
9         10  Ryan Kowalski          3492.93

**Q82 [log]** — Drivers with no delivered shipments. LEFT JOIN with subquery pre-filter + IS NULL.

In [101]:
q82 = """   SELECT d.driver_id, d.name
FROM drivers d
LEFT JOIN (
    SELECT driver_id
    FROM shipments
    WHERE status = 'Delivered'
) AS delivered ON d.driver_id = delivered.driver_id
WHERE delivered.driver_id IS NULL

"""
df = pd.read_sql_query(q82, log)
display(df)

Empty DataFrame
Columns: [driver_id, name]
Index: []

**Q83 [log]** — Shipments where freight_charge is above the average for that specific route. Correlated subquery.

In [102]:
q83 = """ SELECT s.shipment_id,
                s.route_id,
                s.freight_charge AS above_avg_freight
        FROM shipments s 
        WHERE s.freight_charge > ( SELECT 
                        AVG(freight_charge)
                        FROM shipments s2
                        WHERE s2.route_id = s.route_id) 
       ORDER BY above_avg_freight DESC
"""


df = pd.read_sql_query(q83, log)
display(df)

    shipment_id  route_id  above_avg_freight
0          1036         2            4496.88
1          1107         6            4485.35
2          1183         5            4476.63
3          1175         5            4445.74
4          1033         1            4431.12
..          ...       ...                ...
92         1097         1            2350.93
93         1051         1            2348.53
94         1082         4            2176.77
95         1199         4            2072.89
96         1159         6            2067.58

[97 rows x 3 columns]

**Q84 [log]** — For each client, their most recent ship_date. Correlated subquery.

In [103]:
q84 = """   SELECT c.client_id,
                    c.company,
                     (SELECT MAX(ship_date)
                        FROM shipments s
                         WHERE c.client_id = s.client_id
                         ) AS most_recent_ship_date
            FROM clients c 
        

"""
df = pd.read_sql_query(q84, log)
display(df)

   client_id             company most_recent_ship_date
0          1     Maple Retail Co            2024-12-23
1          2   Pacific Goods Ltd            2024-12-12
2          3  Prairie Supply Inc            2024-12-22
3          4      Atlantic Foods            2024-12-04
4          5    Capital Services            2024-12-26
5          6    Northern Freight            2024-12-25
6          7     Rockies Imports            2024-12-14
7          8  Maritime Wholesale            2024-12-19
8          9     Crown Logistics            2024-12-30
9         10      Lakeside Goods            2024-12-10

**Q85 [log]** — Clients whose average freight per shipment is above the company-wide average. Show company and avg_freight.

In [104]:
q85 = """  SELECT c.company,
                ROUND(AVG(freight_charge),2) AS  avg_freight
            FROM shipments s JOIN clients c ON s.client_id = c.client_id
            GROUP BY c.company
            HAVING avg_freight > (SELECT AVG(freight_charge)
                                            FROM shipments
                                            )
                                                    
"""
df = pd.read_sql_query(q85, log)
display(df)

             company  avg_freight
0   Capital Services      2347.36
1    Crown Logistics      2539.94
2   Northern Freight      2413.19
3  Pacific Goods Ltd      2961.83

**Q86 [eco]** — Orders placed by VIP customers only. Subquery with IN to get VIP customer_ids first.

In [105]:
q86 = """  SELECT o.order_id
       FROM orders o JOIN customers c ON o.customer_id = c.customer_id
        WHERE segment = 'VIP'




"""
df = pd.read_sql_query(q86, eco)
display(df)

   order_id
0      1001
1      1004
2      1005
3      1010
4      1015
5      1018
6      1021
7      1027
8      1028

**Q87 [eco]** — Products NEVER ordered by VIP customers. Use NOT IN.

In [106]:
q87 = """ SELECT DISTINCT(product_name)
        FROM order_items 
        WHERE order_id NOT IN (SELECT order_id
                                    FROM orders o JOIN customers c ON o.customer_id = c.customer_id
                                    WHERE segment = 'VIP')
"""
df = pd.read_sql_query(q87, eco)
display(df)

            product_name
0            Phone Stand
1    Mechanical Keyboard
2          Monitor Light
3        Cable Organizer
4               Mousepad
5           Office Chair
6         Lumbar Cushion
7           Laptop Stand
8             HDMI Cable
9           Monitor 27in
10        Screen Cleaner
11            Headphones
12        Desk Organizer
13      Wireless Charger
14    Blue Light Glasses
15            USB-C Dock
16          Gaming Chair
17         Laptop Sleeve
18         Standing Desk
19           Cable Clips
20             4K Webcam
21           Stream Deck
22  Noise Cancel Headset
23          Monitor 32in
24             Desk Lamp
25     Wireless Keyboard
26    Laptop Cooling Pad

**Q88 [log]** — Subquery in FROM: total freight per driver — show only drivers above $10000 total.

In [107]:
q = """ SELECT d.name,
                total_freight.per_driver 

    FROM (  SELECT driver_id,
            SUM(freight_charge) AS per_driver
            FROM shipments s
            GROUP BY driver_id
            ) AS total_freight JOIN drivers d on total_freight.driver_id = d.driver_id
        WHERE total_freight.per_driver > 10000
        ORDER BY total_freight.per_driver DESC
"""

df = pd.read_sql_query(q, log)
display(df)

            name  per_driver
0     Sara Singh    67894.50
1     Linda Park    66159.88
2   Tom Beaumont    50640.03
3   Aisha Diallo    49249.43
4  James Leblanc    46532.18
5    Mike Okafor    45217.99
6  Carlos Rivera    43517.73
7    Priya Mehta    40334.07
8  Jean Tremblay    28333.10
9  Ryan Kowalski    20923.24

In [108]:
q88 = """ SELECT d.name,
                SUM(freight_charge) AS total_freight
    FROM shipments s JOIN drivers d ON s.driver_id = d.driver_id
    GROUP BY d.name
    HAVING total_freight > 10000
    ORDER BY total_freight DESC

    

"""
df = pd.read_sql_query(q88, log)
display(df)

            name  total_freight
0     Sara Singh       67894.50
1     Linda Park       66159.88
2   Tom Beaumont       50640.03
3   Aisha Diallo       49249.43
4  James Leblanc       46532.18
5    Mike Okafor       45217.99
6  Carlos Rivera       43517.73
7    Priya Mehta       40334.07
8  Jean Tremblay       28333.10
9  Ryan Kowalski       20923.24

**Q89 [log]** — For each route, the highest single freight charge on that route. Correlated subquery.

In [109]:
q89 = """ SELECT   r.route_id,
                    r.dest_city,
                (SELECT MAX(freight_charge)
                        FROM shipments s 
                        WHERE s.route_id = r.route_id
                        ) AS highest_freight
    FROM routes r
    
    
    

"""
df = pd.read_sql_query(q89, log)
display(df)

    route_id    dest_city  highest_freight
0          1     Montreal          4431.12
1          2       Ottawa          4496.88
2          3      Halifax          4149.33
3          4      Calgary          3962.20
4          5     Winnipeg          4476.63
5          6     Edmonton          4485.35
6          7     Winnipeg          3976.43
7          8  Quebec City          4343.51
8          9       Ottawa          4377.71
9         10      Moncton          4416.37
10        11  Thunder Bay          4105.84
11        12      Toronto          3044.23

**Q90 [log]** — Shipments where freight_charge equals the maximum on its route. Show shipment_id, route_id, freight_charge.

In [110]:
q90 = """ SELECT shipment_id,
                route_id,
                freight_charge
     FROM shipments s1
     WHERE freight_charge = ( SELECT    MAX(freight_charge)
                                         FROM shipments s2
                                         WHERE s1.route_id = s2.route_id
                                         )
                                
     

"""
df = pd.read_sql_query(q90, log)
display(df)

    shipment_id  route_id  freight_charge
0          1014         4         3962.20
1          1021         9         4377.71
2          1033         1         4431.12
3          1036         2         4496.88
4          1041         3         4149.33
5          1089         7         3976.43
6          1107         6         4485.35
7          1141        10         4416.37
8          1166        11         4105.84
9          1180         8         4343.51
10         1183         5         4476.63
11         1189        12         3044.23

**Q91 [eco]** — Which customer segment has the highest item-level revenue — return just the segment name using a subquery.

In [111]:
q91 = """ SELECT segment 
        FROM order_items oi JOIN orders o ON oi.order_id= o.order_id JOIN customers c ON o.customer_id = c.customer_id
        WHERE (unit_price*quantity) = ( SELECT MAX(unit_price*quantity)
                                        FROM order_items
                                        )
                                        
        

                
"""
df = pd.read_sql_query(q91, eco)
display(df)

  segment
0     VIP

**Q92 [log]** — Average freight per client province using subquery in FROM. Inner: freight per shipment + client province. Outer: AVG per province.

In [112]:
q92 = """   SELECT   freight_per_shipment.province,
                    ROUND(AVG(freight_charge),2) AS avg_per_province
        FROM ( SELECT c.province,
                    s.client_id,
                    s.shipment_id,
                    s.freight_charge
                    FROM shipments s JOIN clients c ON s.client_id = c.client_id
                     ) AS freight_per_shipment
            GROUP BY freight_per_shipment.province

"""
df = pd.read_sql_query(q92, log)
display(df)

  province  avg_per_province
0       AB           2266.64
1       BC           2961.83
2       MB           2413.19
3       NB           2047.63
4       NS           2170.99
5       ON           2233.36

**Q93 [eco]** — For each region: total revenue AND top customer name by spend. Correlated subquery for the top customer.

In [113]:
q93 = """ SELECT o1.region,
       SUM(o1.total_amount) AS total_revenue,
       (SELECT c.name
        FROM orders o2 JOIN customers c ON o2.customer_id = c.customer_id
        WHERE o2.region = o1.region
        AND o2.total_amount = (SELECT MAX(total_amount) 
                               FROM orders o3 
                               WHERE o3.region = o1.region)
        LIMIT 1) AS top_customer
FROM orders o1
GROUP BY o1.region
"""
df = pd.read_sql_query(q93, eco)
display(df)

  region  total_revenue   top_customer
0   East        2417.99  Carlos Mendez
1  North        1695.00       James Wu
2  South        2015.00       Bob Chen
3   West        4590.50  Carlos Mendez

**Q94 [log]** — Clients whose most recent shipment (by ship_date) was cancelled. Correlated subquery for latest date, filter on status.

In [114]:
q94 = """ SELECT c.company,
                s.ship_date
        FROM shipments s JOIN clients c ON s.client_id = c.client_id
        WHERE status = 'cancelled' AND ship_date = (SELECT MAX(ship_date) 
                                                        FROM shipments 
                                                        WHERE client_id = s.client_id)
     
"""
df = pd.read_sql_query(q94, log)
display(df)

Empty DataFrame
Columns: [company, ship_date]
Index: []

**Q95 [eco]** — Full segment report: segment, total_customers, completed_orders, item_revenue, avg_order_value (item grain subquery), Above/Below company avg flag. Order by item_revenue desc.

In [115]:
q95 = """ SELECT c.segment,
                COUNT(DISTINCT c.customer_id) AS customer_count,
                (SELECT COUNT(DISTINCT order_id)
                    FROM orders o2 JOIN customers c2 ON o2.customer_id = c2.customer_id
                    WHERE status = 'completed' AND c2.segment= c.segment ) AS completed_orders,
                SUM(oi.quantity*oi.unit_price) AS item_revenue,
                Round(AVG(oi.quantity*oi.unit_price),2) AS avg_order_value,
                CASE WHEN SUM(oi.quantity*oi.unit_price) > (SELECT AVG(oi.quantity*oi.unit_price)
                                                            FROM order_items )
                                                                                           
                     THEN 'Above Avg'
        ELSE 'Below Avg' END AS Above_Below_company_avg
    FROM orders o JOIN order_items oi ON o.order_id = oi.order_id
    JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.segment
    ORDER BY item_revenue DESC 
"""
df = pd.read_sql_query(q95, eco)
display(df)

,segment,customer_count,completed_orders,item_revenue,avg_order_value,Above_Below_company_avg
0,Regular,4,9,3094.49,147.36,Above Avg
1,VIP,3,7,2698.00,168.63,Above Avg
2,New,3,3,1088.00,136.00,Above Avg

**Q96 [log]** — Each driver with total delivered freight AND 'Above'/'Below' company-wide avg flag. Subquery for avg.

In [116]:
q96 = """ SELECT d.name,
            SUM(freight_charge) AS total_delivered_freight,
            CASE WHEN SUM(freight_charge) > (SELECT AVG(freight_charge)
                                                    FROM shipments) THEN 'Above AVG' ELSE 'Below Avg' END AS above_below_avg
        FROM shipments s JOIN drivers d ON s.driver_id = d.driver_id
        WHERE s.status = 'Delivered'
        GROUP BY d.name
        ORDER BY total_delivered_freight DESC   
"""
df = pd.read_sql_query(q96, log)
display(df)

            name  total_delivered_freight above_below_avg
0     Sara Singh                 37379.58       Above AVG
1   Aisha Diallo                 34477.68       Above AVG
2     Linda Park                 33087.99       Above AVG
3  Carlos Rivera                 30453.34       Above AVG
4  James Leblanc                 27825.29       Above AVG
5    Mike Okafor                 27143.77       Above AVG
6   Tom Beaumont                 22524.42       Above AVG
7    Priya Mehta                 12719.59       Above AVG
8  Ryan Kowalski                  9318.18       Above AVG
9  Jean Tremblay                  6682.19       Above AVG

**Q97 [log]** — For each client segment, the top driver by total freight served. Correlated subquery.

In [117]:
q97 = """ SELECT c.segment,
       (SELECT d1.name
        FROM drivers d1 
        JOIN shipments s1 ON d1.driver_id = s1.driver_id 
        JOIN clients c1 ON s1.client_id = c1.client_id
        WHERE c1.segment = c.segment
        GROUP BY d1.name
        HAVING SUM(s1.freight_charge) = (SELECT MAX(total)
                                         FROM (SELECT SUM(freight_charge) AS total
                                               FROM shipments s2 
                                               JOIN clients c2 ON s2.client_id = c2.client_id
                                               WHERE c2.segment = c.segment
                                               GROUP BY s2.driver_id) AS driver_totals)
        LIMIT 1) AS top_driver_by_freight
FROM shipments s JOIN clients c ON s.client_id = c.client_id
GROUP BY c.segment

"""
df = pd.read_sql_query(q97, log)
display(df)

      segment top_driver_by_freight
0  Enterprise            Sara Singh
1  Government         Carlos Rivera
2         SMB          Tom Beaumont

**Q98 [eco]** — Customers whose most recent order was a cancellation. Correlated subquery.

In [118]:
q98 = """ SELECT c.name
FROM orders o JOIN customers c ON o.customer_id = c.customer_id
WHERE status = 'cancelled' AND order_date = (SELECT 
                                                MAX(order_date)
                                                FROM orders
                                                WHERE customer_id=o.customer_id
                                                )


"""
df = pd.read_sql_query(q98, eco)
display(df)

           name
0    Priya Nair
1  Alice Martin

**Q99 [log]** — Top route by total delivered freight per destination province. Use subquery to get route totals, then find the max per province.

In [119]:
q99 = """ SELECT r.route_id,
                r.dest_province,
                (SELECT SUM(freight_charge)
                  FROM shipments s1
                  WHERE s.route_id = s1.route_id AND status = 'Delivered'
                     ) AS total_delivered_freight

FROM shipments s JOIN routes r ON s.route_id = r.route_id
WHERE s.status = 'Delivered'
GROUP BY r.dest_province
HAVING total_delivered_freight = (SELECT MAX(total)
                                         FROM (SELECT SUM(freight_charge) AS total
                                               FROM shipments s2 
                                               JOIN routes r2 ON s2.route_id = r2.route_id
                                               WHERE r.dest_province = r2.dest_province AND status = 'Delivered'
                                               GROUP BY r2.route_id) AS dest_total)
ORDER BY total_delivered_freight DESC

"""
df = pd.read_sql_query(q99, log)
display(df)

   route_id dest_province  total_delivered_freight
0         2            ON                 30365.64
1         5            MB                 25405.78
2        10            NB                 24737.20
3         3            NS                 19162.14

**Q100 — CAPSTONE (two parts)**

**Part A [eco]** — Full ecommerce segment report: segment, customer_count (COUNT DISTINCT), completed_orders (COUNT DISTINCT), item_revenue (SUM oi.quantity * oi.unit_price), avg_order_value at item grain, top_category per segment (correlated subquery), Above/Below company avg flag. Order by item_revenue desc.

**Part B [log]** — Full logistics driver report: driver name, province, total_shipments, total_freight, avg_freight per shipment (rounded 2dp), top_route (most freight, correlated subquery), Above/Below company avg freight flag. Delivered only. Order by total_freight desc.

In [120]:
q100a = """
        WITH per_segment AS ( SELECT c.segment,
                                        COUNT(DISTINCT c.customer_id) AS customer_count,
                                         COUNT(DISTINCT o.order_id) AS order_count,
                                        SUM(oi.quantity * oi.unit_price) AS revenue,
                                        AVG(oi.quantity * oi.unit_price) AS avg_order_value
    FROM orders o JOIN customers c ON o.customer_id = c.customer_id JOIN order_items oi ON o.order_id = oi.order_id
    WHERE o.status = 'completed'
    GROUP BY c.segment),

    category_revenue AS ( SELECT c.segment,
                                oi.category,
                                SUM(oi.quantity * oi.unit_price) AS cat_revenue
    FROM orders o JOIN customers c ON o.customer_id = c.customer_id JOIN order_items oi ON o.order_id = oi.order_id
        WHERE o.status = 'completed'
     GROUP BY c.segment, oi.category),
   
   
   category_rank AS (
    SELECT segment,
           category,
           RANK() OVER (PARTITION BY segment ORDER BY cat_revenue DESC) AS rnk
    FROM category_revenue),

   avg AS (
    SELECT AVG(oi.quantity * oi.unit_price) AS company_avg
    FROM order_items oi JOIN orders o ON oi.order_id = o.order_id
     WHERE o.status = 'completed')
   
SELECT ps.segment,
       ps.customer_count,
       ps.order_count,
       ps.revenue,
       ROUND(ps.avg_order_value, 2) AS avg_order_value,
       cr.category AS top_category,
       (CASE WHEN ps.revenue > avg.company_avg THEN 'Above' ELSE 'Below' END) AS flag
FROM per_segment ps JOIN category_rank cr ON ps.segment = cr.segment AND cr.rnk = 1 CROSS JOIN avg
ORDER BY ps.revenue DESC

"""
df = pd.read_sql_query(q100a, eco)
display(df)

,segment,customer_count,order_count,revenue,avg_order_value,top_category,flag
0,VIP,3,7,2516.0,193.54,Electronics,Above
1,Regular,4,9,2111.5,124.21,Electronics,Above
2,New,3,3,489.0,163.00,Electronics,Above

**Part B [log]** — Full logistics driver report: driver name, province, total_shipments, total_freight, avg_freight per shipment (rounded 2dp), top_route (most freight, correlated subquery), Above/Below company avg freight flag. Delivered only. Order by total_freight desc.

In [121]:
# Part B — Logistics driver report
q100b = """
WITH per_driver AS (    SELECT  s.driver_id, 
                                d.name, 
                                d.province,
                                COUNT(shipment_id) AS total_shipments,
                                SUM(s.freight_charge) AS total_freight,
                                ROUND(AVG(freight_charge), 2) AS avg_freight
                         FROM shipments s JOIN drivers d ON s.driver_id = d.driver_id 
                        GROUP BY s.driver_id, d.name, d.province),

        per_route AS (  SELECT route_id,
                                driver_id,
                                SUM(freight_charge) AS  route_freight

                        FROM shipments
                        GROUP BY route_id, driver_id),
                 
        route_rank AS (SELECT   driver_id,
                                route_id,
                                route_freight,
                                RANK() OVER (PARTITION BY driver_id ORDER BY route_freight DESC) AS rnk
                                FROM per_route),
          
        avg AS ( SELECT avg(total_freight) AS company_avg
        FROM per_driver)             

        SELECT pd.name,
                pd.province,
                pd.total_shipments,
                pd.total_freight,
                pd.avg_freight,
                (CASE WHEN pd.total_freight > a.company_avg THEN 'Above' ELSE 'Below' END) AS flag
        FROM per_driver pd JOIN route_rank rr ON pd.driver_id = rr.driver_id CROSS JOIN avg a WHERE rr.rnk = 1
        ORDER BY total_freight DESC
                                
                       

                            
                         

"""
df = pd.read_sql_query(q100b, log)
display(df)

            name province  total_shipments  total_freight  avg_freight   flag
0     Sara Singh       BC               27       67894.50      2514.61  Above
1     Linda Park       BC               24       66159.88      2756.66  Above
2   Tom Beaumont       AB               22       50640.03      2301.82  Above
3   Aisha Diallo       QC               23       49249.43      2141.28  Above
4  James Leblanc       NS               22       46532.18      2115.10  Above
5    Mike Okafor       ON               21       45217.99      2153.24  Below
6  Carlos Rivera       MB               17       43517.73      2559.87  Below
7    Priya Mehta       ON               21       40334.07      1920.67  Below
8  Jean Tremblay       QC               10       28333.10      2833.31  Below
9  Ryan Kowalski       ON               13       20923.24      1609.48  Below